export const cards = [
  {
    id: 1,
    name: 'Anniversary 1',
    categories: ['celebrate', 'anniversary', 'wife'],
    pages: [
      {
        name: 'front',
        background:
          'http://res.cloudinary.com/dx2bh212j/image/upload/v1604065106/ewiwtlw6bocshtrmwrdt.jpg',
        backgroundPosition: 'top',
        sections: [
          {
            id: '40064cfa-6532-4792-943b-f1650b8a6e6d',
            userInput: 'With love...',
            height: 200,
            color: '#9f9f32',
            fontFamily: 'Verdana',
            fontSize: '2.5rem',
            isItalic: true,
            isBold: false,
            justifyContent: 'center',
            alignItems: 'center',
          },
        ],
      },
      { name: 'inside-left', sections: [] },
      {
        name: 'inside-right',
        sections: [
          {
            id: 'b109d831-c24d-4ad6-8ecf-27bf0c8e1e89',
            height: 200,
            fontSize: '2rem',
            justifyContent: 'center',
            alignItems: 'center',
            color: '#383333',
            userInput: 'Lots of love',
            fontFamily: 'Verdana',
            isItalic: true,
          },
          {
            id: '3774d37c-1e49-414c-bc62-a4fec11de23e',
            userInput: 'To the next 20 years...',
            height: 200,
            color: '#383333',
            fontSize: '1.6rem',
            isItalic: false,
            isBold: false,
            justifyContent: 'center',
            alignItems: 'center',
            fontFamily: 'Verdana',
          },
          {
            id: '08f58058-ed40-4b51-bae2-68b3b8b4c103',
            height: 300,
            fontSize: '1.6rem',
            justifyContent: 'center',
            alignItems: 'center',
            color: '#383333',
            userInput: 'Your loving wife',
            fontFamily: 'Verdana',
          },
        ],
      },
      { name: 'back', sections: [] },
    ],
  },
  {
    id: 2,
    name: 'Anniversary 2',
    categories: ['celebrate', 'anniversary', 'wedding', 'husband'],
    pages: [
      {
        name: 'front',
        background:
          'http://res.cloudinary.com/dx2bh212j/image/upload/v1604064207/xdqhhtknl2eajaunodpx.jpg',
        backgroundPosition: 'top',
        sections: [
          {
            id: '40064cfa-6532-4792-943b-f1650b8a6e6d',
            userInput: 'Happy Anniversary',
            height: 200,
            color: '#383333',
            fontFamily: 'Georgia',
            fontSize: '1.6rem',
            isItalic: true,
            isBold: false,
            justifyContent: 'center',
            alignItems: 'center',
          },
        ],
      },
      { name: 'inside-left', sections: [] },
      {
        name: 'inside-right',
        sections: [
          {
            id: '3774d37c-1e49-414c-bc62-a4fec11de23e',
            userInput: 'To my wife',
            height: 200,
            color: '#383333',
            fontSize: '2.5rem',
            isItalic: true,
            isBold: false,
            justifyContent: 'center',
            alignItems: 'center',
            fontFamily: 'Georgia',
          },
          {
            id: '55991c09-e593-48a9-af64-63177de503a7',
            userInput: 'Happy 4th Anniversary!',
            height: 200,
            color: '#383333',
            fontSize: '1.6rem',
            isItalic: false,
            isBold: false,
            justifyContent: 'center',
            alignItems: 'center',
            fontFamily: 'Georgia',
          },
          {
            id: 'd7d56f95-93db-4bdc-999b-3a21a5a451f9',
            height: 200,
            fontSize: '1.6rem',
            justifyContent: 'center',
            alignItems: 'center',
            color: '#af5b3f',
            userInput: 'Love from your husband\nxxx',
            fontFamily: 'Georgia',
            isItalic: true,
          },
        ],
      },
      {
        name: 'back',
        sections: [],
        background:
          'http://res.cloudinary.com/dx2bh212j/image/upload/v1604064557/evoo3wxwunzju7n3croq.jpg',
        backgroundPosition: 'center',
      },
    ],
  },
  {
    id: 3,
    name: 'Birthday 1',
    categories: ['birthday'],
    pages: [
      {
        name: 'front',
        background:
          'http://res.cloudinary.com/dx2bh212j/image/upload/v1604069731/gabuddi5diwuype1xntq.jpg',
        backgroundPosition: 'top',
        sections: [],
      },
      { name: 'inside-left', sections: [] },
      {
        name: 'inside-right',
        sections: [
          {
            id: '3774d37c-1e49-414c-bc62-a4fec11de23e',
            userInput: 'Happy Birthday!',
            height: 200,
            color: '#ae427f',
            fontSize: '2.5rem',
            isItalic: true,
            isBold: false,
            justifyContent: 'center',
            alignItems: 'center',
            fontFamily: 'Georgia',
          },
          {
            id: '55991c09-e593-48a9-af64-63177de503a7',
            userInput: 'Have an amazing day',
            height: 200,
            color: '#b46b4a',
            fontSize: '2rem',
            isItalic: false,
            isBold: false,
            justifyContent: 'center',
            alignItems: 'center',
            fontFamily: 'Georgia',
          },
          {
            id: 'd7d56f95-93db-4bdc-999b-3a21a5a451f9',
            height: 200,
            fontSize: '1.6rem',
            justifyContent: 'center',
            alignItems: 'center',
            color: '#ae427f',
            userInput: 'Love from all the family\n xxx',
            fontFamily: 'Georgia',
            isItalic: true,
          },
        ],
      },
      { name: 'back', sections: [], backgroundPosition: 'center' },
    ],
  },
  {
    id: 4,
    name: 'Birthday 2',
    categories: ['birthday', 'children'],
    pages: [
      {
        name: 'front',
        background:
          'http://res.cloudinary.com/dx2bh212j/image/upload/v1604070114/fw4uqv5yvjur9lezf6z1.png',
        backgroundPosition: 'top',
        sections: [],
      },
      {
        name: 'inside-left',
        sections: [
          {
            id: '910e4047-78f7-4e88-84b9-f415f30e6428',
            height: 600,
            fontSize: '2.5rem',
            justifyContent: 'center',
            alignItems: 'center',
            color: '#66d6ab',
            userInput: 'Enjoy Your PARTY!!!',
            fontFamily: 'Comic Sans MS',
            isItalic: true,
          },
        ],
      },
      {
        name: 'inside-right',
        sections: [
          {
            id: '3774d37c-1e49-414c-bc62-a4fec11de23e',
            userInput: 'Happy 10th Birthday!',
            height: 300,
            color: '#ae427f',
            fontSize: '2rem',
            isItalic: true,
            isBold: false,
            justifyContent: 'center',
            alignItems: 'center',
            fontFamily: 'Georgia',
          },
          {
            id: 'd7d56f95-93db-4bdc-999b-3a21a5a451f9',
            height: 300,
            fontSize: '1.6rem',
            justifyContent: 'center',
            alignItems: 'center',
            color: '#ae427f',
            userInput: 'Love from your BIG sister\n',
            fontFamily: 'Georgia',
            isItalic: true,
          },
        ],
      },
      {
        name: 'back',
        sections: [],
        backgroundPosition: 'bottom',
        background:
          'http://res.cloudinary.com/dx2bh212j/image/upload/v1604070468/wzhpt7ccmgacilyarsgc.jpg',
      },
    ],
  },
  {
    id: 5,
    name: 'Halloween 1',
    categories: ['halloween'],
    pages: [
      {
        name: 'front',
        background:
          'http://res.cloudinary.com/dx2bh212j/image/upload/v1604070607/qdo95xrxvvoihhvreh7y.jpg',
        backgroundPosition: 'top',
        sections: [
          {
            id: '658eeee5-cad3-4243-abb8-395c06bbb84f',
            height: 200,
            fontSize: '2rem',
            justifyContent: 'center',
            alignItems: 'center',
            color: '#e29417',
            userInput: 'Happy Haunting!',
            fontFamily: 'Comic Sans MS',
          },
        ],
      },
      {
        name: 'inside-left',
        sections: [
          {
            id: '910e4047-78f7-4e88-84b9-f415f30e6428',
            height: 300,
            fontSize: '1.6rem',
            justifyContent: 'center',
            alignItems: 'center',
            color: '#e26d16',
            userInput: 'Hope your day doesn\'t "suck"',
            fontFamily: 'Comic Sans MS',
            isItalic: false,
          },
          {
            id: '38fa2a8d-b9b5-4ac4-bc3b-3c82abfbb617',
            height: 300,
            fontSize: '1.6rem',
            justifyContent: 'center',
            alignItems: 'center',
            color: '#e26d16',
            userInput: 'like a vampire...',
            fontFamily: 'Comic Sans MS',
          },
        ],
      },
      {
        name: 'inside-right',
        sections: [
          {
            id: '3774d37c-1e49-414c-bc62-a4fec11de23e',
            userInput: 'Why did the ghost go into \nthe bar?\n\nFor the Boos.',
            height: 300,
            color: '#e26d16',
            fontSize: '1.6rem',
            isItalic: true,
            isBold: false,
            justifyContent: 'center',
            alignItems: 'center',
            fontFamily: 'Comic Sans MS',
          },
          {
            id: 'd7d56f95-93db-4bdc-999b-3a21a5a451f9',
            height: 300,
            fontSize: '1.6rem',
            justifyContent: 'center',
            alignItems: 'center',
            color: '#e26d16',
            userInput: 'From your spooky fiend\n',
            fontFamily: 'Comic Sans MS',
            isItalic: true,
          },
        ],
      },
      { name: 'back', sections: [], backgroundPosition: 'bottom' },
    ],
  },
  {
    id: 6,
    name: 'Halloween 2',
    categories: ['halloween'],
    pages: [
      {
        name: 'front',
        background:
          'http://res.cloudinary.com/dx2bh212j/image/upload/v1604071504/n0yjbr2pborcpxgn6swc.jpg',
        backgroundPosition: 'top',
        sections: [],
      },
      { name: 'inside-left', sections: [] },
      {
        name: 'inside-right',
        sections: [
          {
            id: '3774d37c-1e49-414c-bc62-a4fec11de23e',
            userInput:
              'Spooks, treats, and yummy \neats. Wishing you the best \nHalloween ever!',
            height: 600,
            color: '#ae427f',
            fontSize: '1.6rem',
            isItalic: true,
            isBold: false,
            justifyContent: 'center',
            alignItems: 'center',
            fontFamily: 'Comic Sans MS',
          },
        ],
      },
      {
        name: 'back',
        sections: [
          {
            id: '7b971c2c-ec1c-44a1-8c83-aa3c267205f2',
            height: 800,
            fontSize: '1.6rem',
            justifyContent: 'center',
            alignItems: 'flex-end',
            color: '#383333',
            userInput: 'Done be too scared.....',
            fontFamily: 'Comic Sans MS',
          },
        ],
        backgroundPosition: 'center',
        background:
          'http://res.cloudinary.com/dx2bh212j/image/upload/v1604071451/p1vpia7hvrpazzshjpnx.jpg',
      },
    ],
  },
  {
    id: 7,
    name: 'Christmas 1',
    categories: ['christmas'],
    pages: [
      {
        name: 'front',
        background:
          'http://res.cloudinary.com/dx2bh212j/image/upload/v1604073511/mt7gsndckat2x39ewtmf.jpg',
        backgroundPosition: 'top',
        sections: [
          {
            id: '3027fb60-5fde-4e35-8313-42cad1d1fdc1',
            height: 600,
            fontSize: '1.6rem',
            justifyContent: 'center',
            alignItems: 'center',
            color: '#3c2c83',
            userInput: 'Wishing you a Merry Christmas!',
            fontFamily: 'Times New Roman',
          },
        ],
      },
      { name: 'inside-left', sections: [] },
      {
        name: 'inside-right',
        sections: [
          {
            id: '3774d37c-1e49-414c-bc62-a4fec11de23e',
            userInput:
              'The best present one can \nhope for this year is to \nspend time together.',
            height: 600,
            color: '#835114',
            fontSize: '1.6rem',
            isItalic: true,
            isBold: false,
            justifyContent: 'center',
            alignItems: 'center',
            fontFamily: 'Times New Roman',
          },
          {
            id: 'e9b78278-fe62-4419-95e4-e71164a42364',
            height: 200,
            fontSize: '1.6rem',
            justifyContent: 'center',
            alignItems: 'center',
            color: '#835114',
            userInput: 'From Chris',
            fontFamily: 'Times New Roman',
            isItalic: true,
          },
        ],
      },
      { name: 'back', sections: [], backgroundPosition: 'center' },
    ],
  },
  {
    id: 8,
    name: 'Christmas 2',
    categories: ['christmas'],
    pages: [
      {
        name: 'front',
        background:
          'http://res.cloudinary.com/dx2bh212j/image/upload/v1604073826/mvinga5ddo51nt5nug3s.jpg',
        backgroundPosition: 'top',
        sections: [],
      },
      { name: 'inside-left', sections: [] },
      {
        name: 'inside-right',
        sections: [
          {
            id: '3774d37c-1e49-414c-bc62-a4fec11de23e',
            userInput: 'The most wonderful time of \nthe year!',
            height: 600,
            color: '#835114',
            fontSize: '1.6rem',
            isItalic: true,
            isBold: false,
            justifyContent: 'center',
            alignItems: 'center',
            fontFamily: 'Times New Roman',
          },
          {
            id: 'e9b78278-fe62-4419-95e4-e71164a42364',
            height: 200,
            fontSize: '1.6rem',
            justifyContent: 'center',
            alignItems: 'center',
            color: '#835114',
            userInput: 'From Chris',
            fontFamily: 'Times New Roman',
            isItalic: true,
          },
        ],
      },
      { name: 'back', sections: [], backgroundPosition: 'center' },
    ],
  },
  {
    id: 9,
    name: 'Christmas 3',
    categories: ['christmas'],
    pages: [
      {
        name: 'front',
        background:
          'http://res.cloudinary.com/dx2bh212j/image/upload/v1604073988/js4hpsxqthcaibn3ragc.jpg',
        backgroundPosition: 'top',
        sections: [
          {
            id: '8ae41920-fa6d-4acf-b948-23c6d80a9575',
            height: 200,
            fontSize: '1.6rem',
            justifyContent: 'center',
            alignItems: 'center',
            color: '#383333',
            userInput: 'Have your best Christmas ever!',
            fontFamily: 'Times New Roman',
            isItalic: true,
          },
        ],
      },
      { name: 'inside-left', sections: [] },
      {
        name: 'inside-right',
        sections: [
          {
            id: '3774d37c-1e49-414c-bc62-a4fec11de23e',
            userInput: 'Merry Christmas with lots of love.',
            height: 600,
            color: '#835114',
            fontSize: '1.6rem',
            isItalic: true,
            isBold: false,
            justifyContent: 'center',
            alignItems: 'center',
            fontFamily: 'Times New Roman',
          },
          {
            id: 'e9b78278-fe62-4419-95e4-e71164a42364',
            height: 200,
            fontSize: '1.6rem',
            justifyContent: 'center',
            alignItems: 'center',
            color: '#835114',
            userInput: 'From Chris',
            fontFamily: 'Times New Roman',
            isItalic: true,
          },
        ],
      },
      { name: 'back', sections: [], backgroundPosition: 'center' },
    ],
  },
  {
    id: 10,
    name: 'Celebrate 1',
    categories: ['celebrate'],
    pages: [
      {
        name: 'front',
        background:
          'http://res.cloudinary.com/dx2bh212j/image/upload/v1604075021/ny2id0ifhrigjekxgg6z.png',
        backgroundPosition: 'top',
        sections: [
          {
            id: '8ae41920-fa6d-4acf-b948-23c6d80a9575',
            height: 100,
            fontSize: '3rem',
            justifyContent: 'center',
            alignItems: 'flex-end',
            color: '#685897',
            userInput: 'Time to celebrate!',
            fontFamily: 'Times New Roman',
            isItalic: true,
            isBold: true,
          },
        ],
      },
      { name: 'inside-left', sections: [] },
      {
        name: 'inside-right',
        sections: [
          {
            id: '3774d37c-1e49-414c-bc62-a4fec11de23e',
            userInput: 'You deserve this!',
            height: 600,
            color: '#685796',
            fontSize: '1.6rem',
            isItalic: true,
            isBold: false,
            justifyContent: 'center',
            alignItems: 'center',
            fontFamily: 'Times New Roman',
          },
          {
            id: 'e9b78278-fe62-4419-95e4-e71164a42364',
            height: 200,
            fontSize: '1.6rem',
            justifyContent: 'center',
            alignItems: 'center',
            color: '#685796',
            userInput: 'From Chris',
            fontFamily: 'Times New Roman',
            isItalic: true,
          },
        ],
      },
      { name: 'back', sections: [], backgroundPosition: 'center' },
    ],
  },
  {
    id: 11,
    name: 'Travel 1',
    categories: ['travel'],
    pages: [
      {
        name: 'front',
        background:
          'http://res.cloudinary.com/dx2bh212j/image/upload/v1604075398/hbxexcw4giajtwxncxvf.jpg',
        backgroundPosition: 'top',
        sections: [
          {
            id: '8ae41920-fa6d-4acf-b948-23c6d80a9575',
            height: 200,
            fontSize: '3rem',
            justifyContent: 'center',
            alignItems: 'center',
            color: '#964353',
            userInput: 'To our explorer...',
            fontFamily: 'Georgia',
            isItalic: false,
            isBold: false,
          },
        ],
      },
      { name: 'inside-left', sections: [] },
      {
        name: 'inside-right',
        sections: [
          {
            id: '3774d37c-1e49-414c-bc62-a4fec11de23e',
            userInput: 'Enjoy your tour of the world.',
            height: 300,
            color: '#964353',
            fontSize: '1.6rem',
            isItalic: true,
            isBold: false,
            justifyContent: 'center',
            alignItems: 'center',
            fontFamily: 'Times New Roman',
          },
          {
            id: 'e9b78278-fe62-4419-95e4-e71164a42364',
            height: 300,
            fontSize: '1.6rem',
            justifyContent: 'center',
            alignItems: 'center',
            color: '#964353',
            userInput: 'See you in 12 months.',
            fontFamily: 'Times New Roman',
            isItalic: true,
          },
        ],
      },
      { name: 'back', sections: [], backgroundPosition: 'center' },
    ],
  },
  {
    id: 12,
    name: 'General 1',
    categories: ['general'],
    pages: [
      {
        name: 'front',
        background:
          'http://res.cloudinary.com/dx2bh212j/image/upload/v1604076374/hpajvkdj9khrtsatncqt.jpg',
        backgroundPosition: 'top',
        sections: [],
      },
      { name: 'inside-left', sections: [] },
      { name: 'inside-right', sections: [] },
      { name: 'back', sections: [], backgroundPosition: 'center' },
    ],
  },
  {
    id: 13,
    name: 'General 2',
    categories: ['general'],
    pages: [
      {
        name: 'front',
        background:
          'http://res.cloudinary.com/dx2bh212j/image/upload/v1604076626/whpjyfd85xgr45zprr8c.jpg',
        backgroundPosition: 'top',
        sections: [],
      },
      { name: 'inside-left', sections: [] },
      { name: 'inside-right', sections: [] },
      { name: 'back', sections: [], backgroundPosition: 'center' },
    ],
  },
  {
    id: 14,
    name: 'General 3',
    categories: ['general'],
    pages: [
      {
        name: 'front',
        background:
          'http://res.cloudinary.com/dx2bh212j/image/upload/v1604076718/vcmaw2stltyrp5538lf9.jpg',
        backgroundPosition: 'top',
        sections: [],
      },
      { name: 'inside-left', sections: [] },
      { name: 'inside-right', sections: [] },
      { name: 'back', sections: [], backgroundPosition: 'center' },
    ],
  },
];
